trigger:
  - main

pool:
  vmImage: "windows-latest"

steps:
  - task: NuGetCommand@2
    inputs:
      command: "restore"
      restoreSolution: "src/Device.Net.Pipelines.sln"
      feedsToUse: "select"

  - task: MSBuild@1
    inputs:
      solution: "src/Device.Net.Pipelines.sln"
      configuration: "Release"

  - task: NuGetCommand@2
    inputs:
      command: "pack"
      packagesToPack: "Build/NuSpecs/*.nuspec"
      versioningScheme: "off"

  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'a579837a-f36e-462f-8492-1a622b5cadb9/f3bac9de-5bde-4855-b10a-d1fe458ac336'